baseURL = 'https://natespace.dev/'
languageCode = 'en-us'
title = 'NateSpace'
author = "Nathan Harris"
DefaultContentLanguage = "en"
ignoreFiles = ['blog/Templates/*']

theme = 'risotto'

sectionPagesMenu = "main"

[params]
noindex = false

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/PeterBParker"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url="mailto:nathanelliottharris@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url="https://www.linkedin.com/in/nathaneharris/"

[params.theme]
palette = 'dracula'

[params.about]
title="Nathan Harris"
description="always improving. never perfect."

[menu]
  [[menu.main]]
  identifier="about"
  name="About"
  url="/"
  weight=10

  [[menu.blog]]
  identifier="blog"
  name="Blog"
  url="/blog/"
  weight=10
